# Generated by Django 4.2.5 on 2023-10-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccounts_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='phone',
        ),
    ]
